### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by wavesailor** [theodorosploumis/drupal-docker-distros#5]
Awesome job - I played around with different distributions - Loved that I could get to the Terminal to play with Drush.

Most of the Drush commands worked except when running `drush up -y` - That fails.
Also the terminal.php does not change directories. I found another option that does seem to work. 
https://github.com/Fluidbyte/PHP-jQuery-Terminal-Emulator

Have you done a write up on how you got this to all work together - It would definitely make an interesting read?
Do you think Docker is ready for production sites yet?

**Comment by theodorosploumis** [comment]
1) In 8.x versions I think `drush up` will not work because it is not allowed by drush. Have you tried this on 7.x versions.

2) Some Distros recently build include a different terminal (see [commit](https://github.com/theodorosploumis/drupal-docker-distros/commit/480ea9455f2642486fff5250b1ac32fd9b27060d)). Currently changing directories is not allowed but you can run commands in different folders.

3) I am about to create a presentation as also as a blog post about creating a PaaS with Docker.

4) Docker is fine for production.

Thanks for your time and your suggestions!
