### ISSUE TITLE
Open Door distribution fails

### ISSUE THREAD

**Issue by wavesailor** [theodorosploumis/drupal-docker-distros#8]
When selecting Open Door, you get the following error message:
`502 Bad Gateway`

This is the URL: http://opendoor-fwpmygyvnq.drupal.distros.bid:8055/

**Comment by wavesailor** [comment]
I got it to work but named it `OpenDD` - It does not seems to work when you name `Open Door`

A new version of the distribution was released yesterday.

**Comment by theodorosploumis** [comment]
The **name** you select is not the issue since it **gets sanitized**. I believe there was an issue with the Host RAM where the proxy could not load the new subdomain.

After recreating the Docker container the website now works (http://opendoor-fwpmygyvnq.drupal.distros.bid:8055/).

For the new version of the Distro please create a pull request.

Thanks.
